# 	LAB 3 SUBMISSION
#
# 	TEAM MEMBERS
# 	--------------------
# 	Prerna - 1410110306
# 	Vishal Gauba - 1410110501
# 	Pranjal Mathur - 1410110296
# 	Saketh Vallakatla - 1410110352

s: server.c c
	gcc server.c -o s -lpthread -w -g

c: client.c
	gcc client.c -o c