#LAB 2 SUBMISSION
#
#
#TEAM MEMBERS
#--------------------
#
#Prerna - 1410110306
#Vishal Gauba - 1410110501
#Pranjal Mathur - 1410110296
#Saketh Vallakatla - 1410110352


s: server_udp.c bitrate.h bit.h c
	gcc -o s server_udp.c -lpthread

c: client_udp_new.c
	gcc -o c client_udp_new.c
